language: haxe

haxe:
  - 3.4.4
  - stable
  - development

# TODO: remove once haxe-react is fixed for Haxe 4+
matrix:
  allow_failures:
    - haxe: development

install:
  - node -v
  - npm install
  - npm run test:init

script:
  - npm run test:all


